# Start AeroSpace at login
start-at-login = true

# Normalizations
# See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse is centered on the focused monitor when focused monitor changes
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Mouse is centered on the focused window when focused window changes
on-focus-changed = 'move-mouse window-lazy-center'

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

[mode.main.binding]
    # Toggle between horizontal and vertical layout within tiles and accordion layouts
    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # Focus window in the given direction
    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # Move window in the given direction
    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Resize window
    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Go to workspace
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    # Move window (node) to workspace
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    # Move workspace to next monitor
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Enter service mode
    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'

# Service mode
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    # Reload config
    esc = ['reload-config', 'mode main']

# Move Arc to workspace 1
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1'

# Move Zen to workspace 1
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 1'

# Move WezTerm to workspace 2
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 2'

# Move Notes to workspace 3
[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'move-node-to-workspace 3'

# Move Notion to workspace 4
[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 4'

# Move Notion Calendar to workspace 4
[[on-window-detected]]
if.app-id = 'com.cron.electron'
run = 'move-node-to-workspace 4'

# Move Notion Mail to workspace 4
[[on-window-detected]]
if.app-id = 'notion.mail.id'
run = 'move-node-to-workspace 4'

# Move Figma to workspace 5
[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace 5'

# Move ChatGPT to workspace 6
[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace 6'

# Move Claude to workspace 6
[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = 'move-node-to-workspace 6'

# Move LM Studio to workspace 6
[[on-window-detected]]
if.app-id = 'ai.elementlabs.lmstudio'
run = 'move-node-to-workspace 6'

# Open Finder in floating mode
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

# Open Bitwarden in floating mode
[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'layout floating'

# Open Activity Monitor in floating mode
[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

# Open OrbStack in floating mode
[[on-window-detected]]
if.app-id = 'dev.kdrag0n.MacVirt'
run = 'layout floating'

# Open Discord in floating mode
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'layout floating'

# Open ProtonVPN in floating mode
[[on-window-detected]]
if.app-id = 'ch.protonvpn.mac'
run = 'layout floating'
