{...}: {
  username = "shu";
  userFullname = "Ushira Dineth";
  userEmail = "ushiradineth@gmail.com";
  workEmail = "ushira@surge.global";
  timezone = "Asia/Colombo";
  initialHashedPassword = "$7$CU..../....KjEeil1WOr4PSRfQN.8VV/$2zumAfm4nO/iXctrrA7GLDb/Cx5YVJwus29nzp42ASD"; # Generated by `mkpasswd -m scrypt`
  authorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICG/8RWB3RvaLc9T3vGy7Gm4+tOYZwVdodE28YHXr98t shu@shu"
  ];
  hostAddresses = {
    shu = "192.168.1.2";
    shutm = "192.168.64.3";
    shupi = "192.168.1.13";
    # Add shulab/shuos once their static IPs are assigned.
  };
}
