{...}: {
  username = "shu";
  userFullname = "Ushira Dineth";
  userEmail = "ushiradineth@gmail.com";
  workEmail = "ushira@surge.global";
  timezone = "Asia/Dubai";
  initialHashedPassword = "$7$CU..../....KjEeil1WOr4PSRfQN.8VV/$2zumAfm4nO/iXctrrA7GLDb/Cx5YVJwus29nzp42ASD"; # Generated by `mkpasswd -m scrypt`
  authorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICG/8RWB3RvaLc9T3vGy7Gm4+tOYZwVdodE28YHXr98t shu@shu"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIENBNOySe2dCyxJgyZujogj0Fs5rUeXzd97P9NmDujfQ shu@shulab"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKjBz32Mi31WhyjZJpYTjtP/NcT+JDOcjqNlIfNUXqGj shu@shuos"
  ];
}
