{...}: let
  publicKeys = {
    shu = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICG/8RWB3RvaLc9T3vGy7Gm4+tOYZwVdodE28YHXr98t shu@shu";
    shupi = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZl3bh9/8hTnd4bGE46sX247Uhyzid/168ytiFy4/Zq shu@shupi";
    shuos = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKjBz32Mi31WhyjZJpYTjtP/NcT+JDOcjqNlIfNUXqGj shu@shuos";
  };
in {
  username = "shu";
  userFullname = "Ushira Dineth";
  userEmail = "ushiradineth@gmail.com";
  workEmail = "ushira@surge.global";
  timezone = "Asia/Colombo";
  gpgKeyId = "F5672742C84DB527";
  workGpgKeyId = "9EF49938B863E7DF";
  initialHashedPassword = "$7$CU..../....KjEeil1WOr4PSRfQN.8VV/$2zumAfm4nO/iXctrrA7GLDb/Cx5YVJwus29nzp42ASD"; # Generated by `mkpasswd -m scrypt`
  hostAddresses = {
    shu = "192.168.1.2";
    shutm = "192.168.64.3";
    shupi = "100.74.32.50";
    shuos = "192.168.1.5";
    # Add shulab once their static IPs are assigned.
  };
  publicKeys = publicKeys;
  authorizedKeys = [publicKeys.shu publicKeys.shuos]; # Authourized to access all machines
}
