return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"lua",
				"javascript",
				"angular",
				"astro",
				"bash",
				"css",
				"dockerfile",
				"dot",
				"go",
				"gotmpl",
				"hcl",
				"helm",
				"html",
				"jq",
				"json",
				"markdown",
				"nix",
				"php",
				"prisma",
				"python",
				"rust",
				"sql",
				"tsx",
				"typescript",
				"vue",
				"yaml",
				"terraform",
			},
			highlight = { enable = true, additional_vim_regex_highlighting = true },
			indent = { enable = true },
      autotag = { enable = true },
      incremental_selection = { enable = true },
			auto_install = true, -- Auto install missing parsers when entering a buffer
			sync_install = true,
		})
	end,
}
